# Generated by Django 4.1.9 on 2023-05-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
    migrations.RemoveField(
        model_name='chat',
        name='user_timestamp',
    ),
    migrations.RemoveField(
        model_name='chat',
        name='bot_timestamp',
    ),
]