# Generated by Django 4.1.9 on 2023-05-18 20:17

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20230518_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='bot_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='user_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]